### ISSUE TITLE
Issues with current version

### ISSUE THREAD

**Issue by jaschdoc** [flix/highlightjs-flix#23]
- [x] `enum A(Int32)` is not properly highlighted 
- [x] Basic types are not highlighted in navy and coal themes
- [x] Color of string interpolation is different from the normal code color
- [x] get / set keywords are not highlighted
- [x] Holes are not highlighted
- [ ] Laws are not highlighted
- [ ] Instances are not highlighted

**Comment by magnus-madsen** [comment]
We can get back to these.
