### ISSUE TITLE
`enum` keyword is not highlighted as a keyword

### ISSUE THREAD

**Issue by jaschdoc** [flix/highlightjs-flix#28]

**Comment by magnus-madsen** [comment]
Any idea why this happens?

**Comment by jaschdoc** [comment]
Yes, I think the regex on keywords may be wrong, so line https://github.com/flix/highlightjs-flix/blob/775018968dde26cf3ea348e599338f76152b9167/src/flix.js#L44 should be `beginKeywords: /class|enum/` (or something similar). I.e., a proper regex and not just a string literal with some regex stuff inside.

**Comment by jaschdoc** [comment]
Another possible solution is just to copy-paste the object and replace `class` with `enum` in the `beginKeywords` literal, thus creating something like `const ENUM = { ... };`

**Comment by jaschdoc** [comment]
Another possible fix may simply be to add a list of string literals instead of a regex, but I'm not sure about this. I'll have to check the documentation.
