### ISSUE TITLE
Discussion: What should be highlighted?

### ISSUE THREAD

**Issue by jaschdoc** [flix/highlightjs-flix#7]
What other things in the language should have special syntax highlighting in addition to what we have now (keywords, literals, defs, classes)?

- Type annotations?
- Type parameters?
- Nil?
- `???`?
- Effects?
- Datalog?
- Laws?

**Comment by magnus-madsen** [comment]
Our aim is for "good enough". I think we should browse through https://doc.flix.dev and look for anything obvious. If it looks good then we are done.

**Comment by magnus-madsen** [comment]
The only things I noticed:

- It would be nice if built-in types had their own color.
- Perhaps integers could have a color different from identifiers.
- IO could have its own color.
- Names like `java.io.Closeable` could have better formatting.
- Interpolations: https://doc.flix.dev/string-interpolation.html
- Holes: https://doc.flix.dev/holes.html
- Annotations: https://doc.flix.dev/test-framework.html

In any case, I think no more than a few more hours on this is what I would expect. 

Is it possible to have other color schemes? Where do colors come from?

**Comment by jaschdoc** [comment]
> Is it possible to have other color schemes? Where do colors come from?

I think it's an mdbook related thing. Hopefully, it shouldn't be anymore difficult than overriding a few global css / scss variables.

https://rust-lang.github.io/mdBook/format/theme/syntax-highlighting.html#custom-theme

**Comment by jaschdoc** [comment]
Leaving this here for later:
For literals to have their own color we just need to create css rule in the theme.css file and add a selector in the scope mode for highlight.js
https://highlightjs.readthedocs.io/en/latest/css-classes-reference.html
